name: Wheat News Bot
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Intelligence
        run: |
          # Fetch Domestic (India Focus)
          curl -A "Mozilla/5.0" -L "https://news.google.com/rss/search?q=Wheat+India+FCI+MSP+Procurement+Punjab+Haryana&hl=en-IN&gl=IN&ceid=IN:en" > domestic.xml
          # Fetch Global (Trade/Weather Focus)
          curl -A "Mozilla/5.0" -L "https://news.google.com/rss/search?q=Wheat+Russia+IKAR+ABARES+USDA+Production+Price&hl=en-US&gl=US&ceid=US:en" > global.xml
      - name: Save
        run: |
          git config user.name "NewsBot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "Sync Intel" || exit 0
          git push
