name: Wheat News Bot
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Latest Intelligence
        run: |
          # We use -A to mimic a real browser (Chrome)
          # We simplified the query to ensure Google returns results every time
          curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" -L "https://news.google.com/rss/search?q=Wheat+India+Procurement+OR+MSP&hl=en-IN&gl=IN&ceid=IN:en" > domestic.xml
          
          curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" -L "https://news.google.com/rss/search?q=Wheat+Russia+OR+USDA+OR+Production+forecast&hl=en-US&gl=US&ceid=US:en" > global.xml
      
      - name: Save to Repository
        run: |
          git config user.name "WheatBot"
          git config user.email "bot@github.com"
          git add domestic.xml global.xml
          # Only commit if files actually changed
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-sync: $(date)" && git push)
